### ISSUE TITLE
Step 1 - wrong npm function package?

### ISSUE THREAD

**Issue by diberry** [aaronpowell/graphql-typescript-workshop#1]
In the section `How the skeleton was created` references npm package [azure-function-core-tools](https://www.npmjs.com/package/azure-function-core-tools). I believe you _mean_ to reference [azure-functions-core-tools](https://www.npmjs.com/package/azure-functions-core-tools).

**Comment by aaronpowell** [comment]
Yes, you are right. I always stuff that up!
